### ISSUE TITLE
sync in-memory state?

### ISSUE THREAD

**Issue by William-Yeh** [gslin/coscup2015-mysql-hands-on#1]
想問一下，以這種 shared storage/DRBD 方式同步 active/standby MySQL servers 時，會不會有些 in-memory state 沒有跟著 DRBD 同步過去，造成兩邊的 state 不一致？

**Comment by gslin** [comment]
因為 InnoDB 有 crash-safe 特性的關係，所以不會有問題。

**Comment by William-Yeh** [comment]
譬如說，daemon 本身可能有些 in-memory data structure (e.g., cache)。

如果 daemon 沒有預期到 files 會被「daemon自己」以外的人修改，daemon 還會知道哪些 in-memory data structure 已經 dirty 需要 reload 了嗎？

**Comment by gslin** [comment]
InnoDB 做完了。
